name: Reservations
main: de.homerbond005.reservations.Reservations
author: HomerBond005
version: '@PROJECT_VERSION@'
softdepend: [PermissionsEx]
commands:
    reservations:
        description: Main Command.
        usage: Type /<command> help for help.