name: Reservations
main: de.HomerBond005.Reservations.Reservations
author: HomerBond005
version: 2.3.6
softdepend: [PermissionsEx, bPermissions, GroupManager, Vault]
commands:
    reservations:
        description: Main Command.
        usage: Type /<command> help for help.